### ISSUE TITLE
关于如何设置视频拉伸的问题

### ISSUE THREAD

**Issue by xiaye13579** [henryblue/MxVideoPlayer#14]
感谢作者的分享，我有个问题想咨询下，我在写项目的时候有些视频片源可能有问题显示成4:3的，我想拉伸成16:9的，这个该怎么弄呢？

**Comment by henryblue** [comment]
你可以在listener的onVideoSizeChanged中改变MxMediaManager.mCurVideoWidth与MxMediaManager.mCurVideoHeight的值， 来实现视频拉伸
