### ISSUE TITLE
New Help

### ISSUE THREAD

**Issue by vijayakumarksv** [henryblue/MxVideoPlayer#19]
Hi Guys, I have doubt how to stop my video when i click the toggle button.

**Comment by henryblue** [comment]
which toggle button ? you can call ' MxMediaManager.getInstance().getPlayer().stop() ' to stop video.

**Comment by vijayakumarksv** [comment]
Hi bro, How to auto start playing the video

**Comment by vijayakumarksv** [comment]
Hi bro, can you help me , How to auto start the video

**Comment by henryblue** [comment]
You can take a look at the sample code.  call "MxVideoPlayerWidget.autoStartPlay"

**Comment by vijayakumarksv** [comment]
This not working to me plz help you
