### ISSUE TITLE
close window on error

### ISSUE THREAD

**Issue by amjad9636** [henryblue/MxVideoPlayer#2]
close

**Comment by henryblue** [comment]
`
@Override
    public void onCompletion() {
       if (mCurrentState == CURRENT_STATE_ERROR) {
         // add the logic you need
       }
       if ("quit fullscreen") {
          super.onCompletion();
       }
    }
`

**Comment by henryblue** [comment]
@Override 
public void onCompletion() {
       if (mCurrentState == CURRENT_STATE_ERROR) {
           // add the logic you need
        }
       if ("quit fullscreen") {
           super.onCompletion();
        }
 }

**Comment by amjad9636** [comment]
why get error 

![untitled](https://cloud.githubusercontent.com/assets/18345101/23338193/7baa470e-fc1d-11e6-97fb-090b0d7aa24a.png)

and can write logic "action" I went after click try again play video
