### ISSUE TITLE
error for add public void onCompletion

### ISSUE THREAD

**Issue by mrbala4** [henryblue/MxVideoPlayer#3]
hi 

why get error 

@Override
public void onCompletion() {
if (mCurrentState == CURRENT_STATE_ERROR) {
// add the logic you need
}
if ("quit fullscreen") {
super.onCompletion();
}
}

![untitled](https://cloud.githubusercontent.com/assets/26039102/23339332/7cf49486-fc39-11e6-9026-50bc9e46037a.png)

or where add code ? i want after click this icon 

![1 4](https://cloud.githubusercontent.com/assets/26039102/23339402/c2ca261e-fc3a-11e6-9459-e436678fbef3.jpg)

try play video

**Comment by twelveToe** [comment]
I can't write you in freelancer.com
farkhadgojazadeh

**Comment by mrbala4** [comment]
can fix this problem ?

**Comment by twelveToe** [comment]
Yeah I can help you if you provide a little more information. you've set a string as a condition. Therefore compiler doesn't know what you want from it

**Comment by mrbala4** [comment]
you have skype ?
