### ISSUE TITLE
error void onCompletion

### ISSUE THREAD

**Issue by mrbala4** [henryblue/MxVideoPlayer#4]
hi

my problem.. after clicking icon error auto close windows 

I want change action "auto close windows" to try playing again after click icon

![1 4](https://cloud.githubusercontent.com/assets/26039102/23340744/14657662-fc55-11e6-85f6-10f400257640.jpg)

after add code .. get error 

@Override
public void onCompletion() {
if (mCurrentState == CURRENT_STATE_ERROR) {
// add the logic you need
}
if ("quit fullscreen") {
super.onCompletion();
}
}

![untitled](https://cloud.githubusercontent.com/assets/26039102/23340758/40838b58-fc55-11e6-9da1-92c0f9ac4531.png)

what problem? 

can write code for try play video again

i use simple project https://github.com/henryblue/MxVideoPlayer/tree/master/app

this all file lib ..what file edit

![sssss](https://cloud.githubusercontent.com/assets/26039102/23341594/ff7e5b7e-fc63-11e6-9ca8-fe9148899c49.png)

Thanks a lot

**Comment by henryblue** [comment]
the code is only tip, "quit fullscreen" is also only code annotation. You can change it as follows:
    boolean mIsQuitFullscreen = false;
    @Override
    public void onCompletion() {
        if (mIsQuitFullscreen) {
            super.onCompletion();
        } else {
            // what you want to do
        }
    }

    @Override
    public boolean quitFullscreenOrTinyListener() {
        mIsQuitFullscreen = true;
        boolean result = super.quitFullscreenOrTinyListener();
        mIsQuitFullscreen = false;
        return result;
    }
This will still have some problems, i will fix this bug in the next version.

**Comment by mrbala4** [comment]
Good Now work for v 1.1.0 

I want other 

how fill screen ? no need black background

![picsart_02-18-05 47 40](https://cloud.githubusercontent.com/assets/26039102/23371419/852e8f5a-fd31-11e6-99f0-785c480396e1.jpg)

**Comment by henryblue** [comment]
About "how fill screen ? no need black background", you can do that:
    @Override
    public void onVideoSizeChanged() {
        MxMediaManager.getInstance().mCurVideoWidth = getMeasuredWidth();
        MxMediaManager.getInstance().mCurVideoHeight = getMeasuredHeight();
        super.onVideoSizeChanged();
    }

About "after click button back .. back 2 activity auto ..me click one only".
I do not understand what you mean, hope you can describe in detail

**Comment by henryblue** [comment]
Unfortunately, it is impossible to achieve all the needs, I do not want the logic of the player is too complicated. You can read the source code to see how to modify. Thanks

**Comment by mrbala4** [comment]
ok..

i found other problem 

after play any video and swipe for increase or decrease volume or swipe screen up , down .. the app crash ..also app simple 

problem in  lib
