### ISSUE TITLE
tv上左右键 快进后退没有反应

### ISSUE THREAD

**Issue by as11051105** [henryblue/MxVideoPlayer#5]
RT

**Comment by henryblue** [comment]
测试没有问题, 你看一下你的使用是否和readme上相同.

**Comment by as11051105** [comment]
你好，另外发现个问题， MP4 第一次播放完毕后会再重新播放一次， 提示/AudioTrack: releaseBuffer() track 0x7f627c9c00 disabled due to previous underrun, restarting ， 2次播放完毕后才会调用OnPlayCompletion() 方法， 另外，能不能提供个方法可以重播？谢谢

**Comment by henryblue** [comment]
看代码中的例子, 在OnPlayCompletion中调startPlay进行重播

**Comment by as11051105** [comment]
在tv上播放时，连续多次快进后退 中间的 加载中 的ProgressBar 会一直出现，不会消失 ，会导致 KEYCODE_ENTER 的暂停开始 点击没反应，谢谢~

**Comment by henryblue** [comment]
从你的描述来看, 这不是问题， 加载中图标不消失说明还在缓冲视频， 这个时候肯定 所有的键都不响应，这是正确的行为. 遇到问题我建议你先稍微分析一下，有助于理解并更好的复用代码
