### ISSUE TITLE
hide bottom container

### ISSUE THREAD

**Issue by deepsheth-agile** [henryblue/MxVideoPlayer#7]
How to hide bottom container which includes time, seek bar and full-screen icon. I don't want to set any progress bar on view.

**Comment by henryblue** [comment]
call setAllControlsVisible interface

**Comment by deepsheth-agile** [comment]
I was set this method in the adapter of the list but it visible bottom container.
Check my code
holder.mPlayerWidget.setAllControlsVisible(View.GONE,View.GONE,View.VISIBLE,View.VISIBLE,View.VISIBLE,View.VISIBLE);

**Comment by henryblue** [comment]
Call setAllControlsVisible after startPlay. but if you touch screen bottom container will be shown. you can modify "changeUiShowState(Mode mode)" in MxVideoPlayerWidget

**Comment by deepsheth-agile** [comment]
I was tried to modify "changeUiShowState(Mode mode)" but it's not working properly.
Can you please provide any boolean method for maintaining its visibility?

**Comment by henryblue** [comment]
I don't think this amendment is necessary.

**Comment by deepsheth-agile** [comment]
It's required because in the list I just want to play video on click of the center play button and in some scenarios we just need to play video full screen without bottom container so we can hide it.
If possible can you please set any method to maintain its visibility and update code for same.

**Comment by henryblue** [comment]
ok, i will add in next version. thank you

**Comment by henryblue** [comment]
you can use 1.1.9 version.
setAutoProcessUI(true) and setUIStatusListener() 
you can call setAllControlsVisible in listener
