### ISSUE TITLE
How to use MXVideoPlayer OnCompletion Method?

### ISSUE THREAD

**Issue by solankiranvir** [henryblue/MxVideoPlayer#9]
```
Hello
How to use VideoPlayer OnCompletion method in my activity class?
currently it is only call in your MXVideoPlayer class but now to use it in my appcompat activty class.
can you please help me?
Thanks
```

**Comment by henryblue** [comment]
public class YouPlayer extends MxVideoPlayerWidget {
private Activity mActivity;
public YouPlayer(Activity activity) {
  mActivity = activity;
}
@override
public void onCompletion() {
super.onCompletion();
// call you activity method
mActivity.complete();
}
}
The YouPlayer class you can get pass findviewbyId in activity onCreate 。。

If you do not understand, I have no way of 。。。。。
